// Code generated by sails-client-gen-v2. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct RecourseClientProgram;

impl RecourseClientProgram {
    pub const ROUTE_ID_MARKET: u8 = 1;
    pub const ROUTE_ID_SETTLEMENT: u8 = 2;
}

impl sails_rs::client::Program for RecourseClientProgram {}

pub trait RecourseClient {
    type Env: sails_rs::client::GearEnv;
    fn market(&self) -> sails_rs::client::Service<market::MarketImpl, Self::Env>;
    fn settlement(&self) -> sails_rs::client::Service<settlement::SettlementImpl, Self::Env>;
}

impl<E: sails_rs::client::GearEnv> RecourseClient
    for sails_rs::client::Actor<RecourseClientProgram, E>
{
    type Env = E;
    fn market(&self) -> sails_rs::client::Service<market::MarketImpl, Self::Env> {
        self.service(RecourseClientProgram::ROUTE_ID_MARKET)
    }
    fn settlement(&self) -> sails_rs::client::Service<settlement::SettlementImpl, Self::Env> {
        self.service(RecourseClientProgram::ROUTE_ID_SETTLEMENT)
    }
}
pub trait RecourseClientCtors {
    type Env: sails_rs::client::GearEnv + sails_rs::client::EnvWithCtor;
    /// Deploy-time config: the allowlisted verifier and the economics
    /// constants. No admin key over settled outcomes — no method can
    /// touch a settled job.
    fn create(
        self,
        verifier: ActorId,
        bond_wei: u128,
        slash_wei: u128,
        slash_to_requester_bps: u32,
    ) -> sails_rs::client::PendingCtor<RecourseClientProgram, io::Create, Self::Env>;
}

impl<E: sails_rs::client::GearEnv + sails_rs::client::EnvWithCtor> RecourseClientCtors
    for sails_rs::client::Deployment<RecourseClientProgram, E>
{
    type Env = E;
    fn create(
        self,
        verifier: ActorId,
        bond_wei: u128,
        slash_wei: u128,
        slash_to_requester_bps: u32,
    ) -> sails_rs::client::PendingCtor<RecourseClientProgram, io::Create, Self::Env> {
        self.pending_ctor((verifier, bond_wei, slash_wei, slash_to_requester_bps))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create (verifier: ActorId, bond_wei: u128, slash_wei: u128, slash_to_requester_bps: u32) -> (), 0);
}

pub mod market {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Address(pub H160);
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Job {
        pub id: u64,
        pub spec: JobSpec,
        pub status: Status,
        pub created_at: u64,
        pub quotes: Vec<Quote>,
        pub winner: Option<ActorId>,
        pub awarded_at: Option<u64>,
        pub receipt: Option<Receipt>,
        pub verdict: Option<Verdict>,
        pub settled: Option<Outcome>,
        pub award_reason: Option<String>,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct JobSpec {
        pub requester: ActorId,
        pub escrow_wei: u128,
        pub max_price_wei: u128,
        pub deadline_secs: u32,
        pub verifier_kind: VerifierKind,
        pub criteria_hash: H256,
        pub policy: Policy,
        pub quote_window_secs: u32,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum Outcome {
        Paid,
        Refunded,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum Policy {
        Cheapest,
        Assured,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Quote {
        pub provider: ActorId,
        pub price_wei: u128,
        pub promised_latency_ms: u32,
        pub submitted_at: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Receipt {
        pub output_hash: H256,
        pub model_tag: String,
        pub submitted_at: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum Status {
        Open,
        Awarded,
        Running,
        Delivered,
        Verified,
        Paid,
        Refunded,
        Expired,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Verdict {
        pub pass: bool,
        pub evidence_hash: H256,
        pub verifier: ActorId,
        pub submitted_at: u64,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub enum VerifierKind {
        UnitTestsV1,
        JsonSchemaV1,
    }

    pub trait Market {
        type Env: sails_rs::client::GearEnv;
        /// Award after the quote window closes. Callable by anyone (frontend
        /// calls it, keeper is the backstop). Deterministic and explainable:
        /// the reason (policy + losing quote indices) is stored on the job.
        /// With no valid quotes the job expires and escrow is refunded.
        fn award_job(
            &mut self,
            job_id: u64,
        ) -> sails_rs::client::PendingCall<io::AwardJob, Self::Env>;
        fn balance_of(
            &self,
            who: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        /// Fund a job by debiting your internal balance. Injected-lane method: it
        /// carries no value (escrow is spent from the balance loaded via
        /// `deposit`), so funding is a gasless signature. Escrow must cover the
        /// worst case (escrow >= max price); at settlement the winner is credited
        /// the quoted price and the difference returns to the requester's balance.
        fn create_job(
            &mut self,
            escrow_wei: u128,
            max_price_wei: u128,
            deadline_secs: u32,
            verifier_kind: String,
            criteria_hash: [u8; 32],
            policy: String,
            quote_window_secs: u32,
        ) -> sails_rs::client::PendingCall<io::CreateJob, Self::Env>;
        /// Load your internal balance. This is the ONE gas payment a requester
        /// makes (payable -> L1): value can only enter the program on the classic
        /// lane, because an injected transaction that carries value is purged
        /// before execution (`NonZeroValue`). Once loaded, funding jobs spends
        /// this balance gaslessly on the injected lane. (vault pattern)
        fn deposit(&mut self) -> sails_rs::client::PendingCall<io::Deposit, Self::Env>;
        fn get_job(&self, job_id: u64) -> sails_rs::client::PendingCall<io::GetJob, Self::Env>;
        fn list_jobs(
            &self,
            status: Option<Status>,
            cursor: u64,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListJobs, Self::Env>;
        /// Post a bond and become a quotable provider. One provider per owner.
        fn register_provider(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::RegisterProvider, Self::Env>;
        /// Winner acknowledges the award. Optional on-camera beat between
        /// Awarded and Delivered.
        fn start_job(
            &mut self,
            job_id: u64,
        ) -> sails_rs::client::PendingCall<io::StartJob, Self::Env>;
        /// Quote on an open job. Injected-lane method: never carries value.
        fn submit_quote(
            &mut self,
            job_id: u64,
            price_wei: u128,
            promised_latency_ms: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitQuote, Self::Env>;
        fn top_up_bond(&mut self) -> sails_rs::client::PendingCall<io::TopUpBond, Self::Env>;
        /// Cash an internal balance back out to L1 (the "claim" gas boundary).
        /// Value rides the reply; the caller claims it via mirror.claimValue.
        fn withdraw(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env>;
        /// Withdraw the full bond and deregister. Only with no active job.
        /// Value rides the reply to the caller (vault pattern).
        fn withdraw_bond(&mut self) -> sails_rs::client::PendingCall<io::WithdrawBond, Self::Env>;
    }

    pub struct MarketImpl;

    impl sails_rs::client::Identifiable for MarketImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([18, 194, 57, 212, 69, 113, 133, 12]);
    }

    impl<E: sails_rs::client::GearEnv> Market for sails_rs::client::Service<MarketImpl, E> {
        type Env = E;
        fn award_job(
            &mut self,
            job_id: u64,
        ) -> sails_rs::client::PendingCall<io::AwardJob, Self::Env> {
            self.pending_call((job_id,))
        }
        fn balance_of(
            &self,
            who: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((who,))
        }
        fn create_job(
            &mut self,
            escrow_wei: u128,
            max_price_wei: u128,
            deadline_secs: u32,
            verifier_kind: String,
            criteria_hash: [u8; 32],
            policy: String,
            quote_window_secs: u32,
        ) -> sails_rs::client::PendingCall<io::CreateJob, Self::Env> {
            self.pending_call((
                escrow_wei,
                max_price_wei,
                deadline_secs,
                verifier_kind,
                criteria_hash,
                policy,
                quote_window_secs,
            ))
        }
        fn deposit(&mut self) -> sails_rs::client::PendingCall<io::Deposit, Self::Env> {
            self.pending_call(())
        }
        fn get_job(&self, job_id: u64) -> sails_rs::client::PendingCall<io::GetJob, Self::Env> {
            self.pending_call((job_id,))
        }
        fn list_jobs(
            &self,
            status: Option<Status>,
            cursor: u64,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::ListJobs, Self::Env> {
            self.pending_call((status, cursor, limit))
        }
        fn register_provider(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::RegisterProvider, Self::Env> {
            self.pending_call(())
        }
        fn start_job(
            &mut self,
            job_id: u64,
        ) -> sails_rs::client::PendingCall<io::StartJob, Self::Env> {
            self.pending_call((job_id,))
        }
        fn submit_quote(
            &mut self,
            job_id: u64,
            price_wei: u128,
            promised_latency_ms: u32,
        ) -> sails_rs::client::PendingCall<io::SubmitQuote, Self::Env> {
            self.pending_call((job_id, price_wei, promised_latency_ms))
        }
        fn top_up_bond(&mut self) -> sails_rs::client::PendingCall<io::TopUpBond, Self::Env> {
            self.pending_call(())
        }
        fn withdraw(
            &mut self,
            amount: u128,
        ) -> sails_rs::client::PendingCall<io::Withdraw, Self::Env> {
            self.pending_call((amount,))
        }
        fn withdraw_bond(&mut self) -> sails_rs::client::PendingCall<io::WithdrawBond, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AwardJob (job_id: u64) -> () | String, 0, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(BalanceOf (who: ActorId) -> u128, 1, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(CreateJob (escrow_wei: u128, max_price_wei: u128, deadline_secs: u32, verifier_kind: String, criteria_hash: [u8; 32], policy: String, quote_window_secs: u32) -> u64 | String, 2, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Deposit () -> u128 | String, 3, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetJob (job_id: u64) -> super::Option<super::Job, >, 4, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ListJobs (status: super::Option<super::Status, >, cursor: u64, limit: u32) -> Vec<super::Job>, 5, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(RegisterProvider () -> () | String, 6, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(StartJob (job_id: u64) -> () | String, 7, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SubmitQuote (job_id: u64, price_wei: u128, promised_latency_ms: u32) -> () | String, 8, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(TopUpBond () -> u128 | String, 9, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(Withdraw (amount: u128) -> u128 | String, 10, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(WithdrawBond () -> u128 | String, 11, <super::MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum MarketEvents {
            #[codec(index = 0)]
            Deposited {
                who: Address,
                amount: u128,
                balance: u128,
            },
            #[codec(index = 1)]
            JobAwarded {
                job_id: u64,
                winner: Address,
                reason: String,
            },
            #[codec(index = 2)]
            JobCreated {
                job_id: u64,
                requester: Address,
                max_price_wei: u128,
                escrow_wei: u128,
            },
            #[codec(index = 3)]
            ProviderRegistered { provider: Address, bond_wei: u128 },
            #[codec(index = 4)]
            QuoteSubmitted {
                job_id: u64,
                provider: Address,
                price_wei: u128,
                promised_latency_ms: u32,
            },
            #[codec(index = 5)]
            Withdrawn {
                who: Address,
                amount: u128,
                balance: u128,
            },
        }

        impl MarketEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::Deposited { .. } => 0,
                    Self::JobAwarded { .. } => 1,
                    Self::JobCreated { .. } => 2,
                    Self::ProviderRegistered { .. } => 3,
                    Self::QuoteSubmitted { .. } => 4,
                    Self::Withdrawn { .. } => 5,
                }
            }
        }

        impl sails_rs::client::Event for MarketEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for MarketEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <MarketImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for MarketImpl {
            type Event = MarketEvents;
        }
    }
}

pub mod settlement {
    use super::*;

    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Config {
        pub verifier: ActorId,
        pub bond_wei: u128,
        pub slash_wei: u128,
        pub slash_to_requester_bps: u32,
    }
    #[sails_rs::sails_type(crate = sails_rs)]
    #[derive(PartialEq, Clone, Debug)]
    pub struct Provider {
        pub owner: ActorId,
        pub bond_wei: u128,
        pub jobs_won: u32,
        pub jobs_passed: u32,
        pub jobs_failed: u32,
        pub jobs_expired: u32,
        pub active_job: Option<u64>,
        pub registered_at: u64,
    }

    pub trait Settlement {
        type Env: sails_rs::client::GearEnv;
        /// Anyone can expire an overdue job (keeper is the usual caller, but
        /// liveness must not depend on it). Terminal; counts as a fail.
        fn expire_job(
            &mut self,
            job_id: u64,
        ) -> sails_rs::client::PendingCall<io::ExpireJob, Self::Env>;
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
        fn get_provider(
            &self,
            actor: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetProvider, Self::Env>;
        fn get_retained_wei(&self) -> sails_rs::client::PendingCall<io::GetRetainedWei, Self::Env>;
        fn list_providers(&self) -> sails_rs::client::PendingCall<io::ListProviders, Self::Env>;
        /// Winner delivers. The program stamps time itself; a receipt past the
        /// deadline is rejected so delivery and expiry cannot race.
        fn submit_receipt(
            &mut self,
            job_id: u64,
            output_hash: H256,
            model_tag: String,
        ) -> sails_rs::client::PendingCall<io::SubmitReceipt, Self::Env>;
        /// Allowlisted verifier grades the delivery; settlement runs inline.
        fn submit_verdict(
            &mut self,
            job_id: u64,
            pass: bool,
            evidence_hash: H256,
        ) -> sails_rs::client::PendingCall<io::SubmitVerdict, Self::Env>;
    }

    pub struct SettlementImpl;

    impl sails_rs::client::Identifiable for SettlementImpl {
        const INTERFACE_ID: sails_rs::InterfaceId =
            sails_rs::InterfaceId::from_bytes_8([192, 252, 96, 111, 154, 29, 143, 255]);
    }

    impl<E: sails_rs::client::GearEnv> Settlement for sails_rs::client::Service<SettlementImpl, E> {
        type Env = E;
        fn expire_job(
            &mut self,
            job_id: u64,
        ) -> sails_rs::client::PendingCall<io::ExpireJob, Self::Env> {
            self.pending_call((job_id,))
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
        fn get_provider(
            &self,
            actor: ActorId,
        ) -> sails_rs::client::PendingCall<io::GetProvider, Self::Env> {
            self.pending_call((actor,))
        }
        fn get_retained_wei(&self) -> sails_rs::client::PendingCall<io::GetRetainedWei, Self::Env> {
            self.pending_call(())
        }
        fn list_providers(&self) -> sails_rs::client::PendingCall<io::ListProviders, Self::Env> {
            self.pending_call(())
        }
        fn submit_receipt(
            &mut self,
            job_id: u64,
            output_hash: H256,
            model_tag: String,
        ) -> sails_rs::client::PendingCall<io::SubmitReceipt, Self::Env> {
            self.pending_call((job_id, output_hash, model_tag))
        }
        fn submit_verdict(
            &mut self,
            job_id: u64,
            pass: bool,
            evidence_hash: H256,
        ) -> sails_rs::client::PendingCall<io::SubmitVerdict, Self::Env> {
            self.pending_call((job_id, pass, evidence_hash))
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ExpireJob (job_id: u64) -> () | String, 0, <super::SettlementImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetConfig () -> super::Config, 1, <super::SettlementImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetProvider (actor: ActorId) -> super::Option<super::Provider, >, 2, <super::SettlementImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(GetRetainedWei () -> u128, 3, <super::SettlementImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(ListProviders () -> Vec<super::Provider>, 4, <super::SettlementImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SubmitReceipt (job_id: u64, output_hash: H256, model_tag: String) -> () | String, 5, <super::SettlementImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
        sails_rs::io_struct_impl!(SubmitVerdict (job_id: u64, pass: bool, evidence_hash: H256) -> () | String, 6, <super::SettlementImpl as sails_rs::client::Identifiable>::INTERFACE_ID);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[sails_rs::sails_type(crate = sails_rs)]
        #[derive(PartialEq, Debug)]
        pub enum SettlementEvents {
            #[codec(index = 0)]
            JobExpired { job_id: u64 },
            #[codec(index = 1)]
            JobSettled {
                job_id: u64,
                paid: u32,
                paid_wei: u128,
                refunded_wei: u128,
                slashed_wei: u128,
            },
            #[codec(index = 2)]
            ReceiptSubmitted { job_id: u64, output_hash: [u8; 32] },
            #[codec(index = 3)]
            VerdictSubmitted { job_id: u64, pass: u32 },
        }

        impl SettlementEvents {
            pub fn entry_id(&self) -> u16 {
                match self {
                    Self::JobExpired { .. } => 0,
                    Self::JobSettled { .. } => 1,
                    Self::ReceiptSubmitted { .. } => 2,
                    Self::VerdictSubmitted { .. } => 3,
                }
            }
        }

        impl sails_rs::client::Event for SettlementEvents {
            fn decode_event(
                route: &sails_rs::client::RouteIdx,
                payload: impl AsRef<[u8]>,
            ) -> Result<Self, sails_rs::scale_codec::Error> {
                sails_rs::client::decode_event_v2::<Self>(route.0, payload)
            }
        }

        impl sails_rs::client::Identifiable for SettlementEvents {
            const INTERFACE_ID: sails_rs::InterfaceId =
                <SettlementImpl as sails_rs::client::Identifiable>::INTERFACE_ID;
        }

        impl sails_rs::client::ServiceWithEvents for SettlementImpl {
            type Event = SettlementEvents;
        }
    }
}
